using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System;



/// <summary>
/// 事件定义
/// </summary>
public enum EVENT_TYPE
{
    EVENT_NONE = 0,

    EVENT_LOGIC_SYSTEMSETTING_CHANGE,
    EVENT_LOGIC_REFRESH_MONEY,

    EVENT_LOGIC_ENTER_STAGE,
    EVENT_LOGIC_PASS_STAGE,

    EVENT_LOGIC_START_WAVE,
    EVENT_LOGIC_CAST_DAMAGE,
    EVENT_LOGIC_CAST_DAMAGE_FINISH,
    EVENT_LOGIC_MONSTER_SKILL,
    EVENT_LOGIC_MONSTER_SKILL_FINISH,
    EVENT_LOGIC_ADD_ROLE_HP,
    EVENT_LOGIC_ROUND_END,

    EVENT_LOGIC_IAP_REQ,
    EVENT_LOGIC_IAP_SUCESS

}
